package com.example.demo.annotation;

public enum TipoDadoEngineEnum {

	CHARACTER,CHARACTER_VARYING,CHARACTER_LARGE,OBJECT,VARCHAR_IGNORECASE,BINARY,
	BINARY_VARYING,BINARY_LARGE_OBJECT,BOOLEAN,TINYINT,SMALLINT,INTEGER,BIGINT,
	NUMERIC,REAL,DOUBLE_PRECISION,DECFLOAT,DATE,TIME,TIME_WITH_TIME_ZONE,TIMESTAMP,
	TIMESTAMP_WITH_TIME_ZONE,INTERVAL,JAVA_OBJECT,ENUM,GEOMETRY,JSON,UUID,ARRAY,ROW;
}
